import { translateWithParams, type Locale } from "../i18n";
import { getI18nLocale } from "../i18n/runtime";

/**
 * Activity log messages are mostly user content (commit messages, PR titles) and are shown as is.
 * A few are generated by the backend in a fixed language ("3 commits", "Merged PR #5",
 * "PR #5: комментарий от ivan"); those are re-rendered in the UI language, old rows included.
 * Returns null when the message only repeats the action already shown ("Repository created").
 */
export function activityMessageText(
  type: string,
  message: string | null | undefined,
  locale: Locale = getI18nLocale(),
): string | null {
  const text = (message ?? "").trim();
  if (!text) return null;
  const tp = (key: string, params: Record<string, string | number>) =>
    translateWithParams(locale, `activityText.${key}`, params);

  if (type === "repo_created" || type === "repo_deleted" || type === "create" || type === "delete") {
    if (/^Repository (created|deleted)$/i.test(text)) return null;
  }

  let m = text.match(/^(\d+) commits?$/i);
  if (m && type === "push") return tp("commits", { n: Number(m[1]) });

  m = text.match(/^(?:Merged PR #(\d+)|PR #(\d+) merged)$/i);
  if (m && (type === "pr_merge" || type === "merge")) return `PR #${m[1] ?? m[2]}`;

  if (type === "pr_comment") {
    m = text.match(/^PR #(\d+): комментарий от (.+)$/);
    if (m) return tp("prCommentBy", { number: m[1], login: m[2] });
    m = text.match(/^PR #(\d+) от (\S+): ([\s\S]*)$/);
    if (m) return tp("prCommentByPreview", { number: m[1], login: m[2], preview: m[3] });
  }
  return text;
}
